<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net8.0-windows;net472</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <AssemblyVersion>0.1.0</AssemblyVersion>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>../../../sign/END.snk</AssemblyOriginatorKeyFile>
        <PublicSign>false</PublicSign>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
        <DelaySign>true</DelaySign>
        <NoWarn>CA1869</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <OutputPath>../../../Output/Debug/</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <OutputPath>../../../Output/Release/</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="2.0.0" />
        <PackageReference Include="NLog" Version="5.4.0" />
    </ItemGroup>
    
    <ItemGroup>
        <None Include="../../../README.md" Pack="true" PackagePath="\"/>
        <None Include="../../../LICENSE.md" Pack="true" PackagePath=""/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\END.Config\END.Config.csproj" />
      <ProjectReference Include="..\END.Embedded\END.Embedded.csproj" />
    </ItemGroup>

</Project>
